### ISSUE TITLE
Недефиниран случай в задача

### ISSUE THREAD

**Issue by kaykayehnn** [SoftUni/Programming-Basics-Book-CSharp-BG#229]
## Линк към файла
https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/blob/master/chapter-09-problems-for-champions-part-2.md
## Описание
В задачата Passion Days никъде не е казано, че покупка на стойност 0 лв(символ '%' при налична сума 0) не трябва да се извършва(да се инкрементира броя направени покупки). Без това пояснение последния тест в джъдж не минава, а не се подразбира. Също има грешка от невнимание в ограниченията.
## Текущ текст
Броят на стрингове между "mall.Enter" и "mall.Enter" ще в интервала: [1-20].
## Текст след поправката
Броят на стрингове между "mall.Enter" и "mall.Exit" ще в интервала: [1-20].

**Comment by udarensamolet** [comment]
Fixed with [d6efa8a](https://github.com/SoftUni/Programming-Basics-Book-CSharp-BG/commit/d6efa8af7eee9dc968fb0041e30330398e905add).

Относно другата забележка - тъй като задачата е от глава "Задачи за шампиони", то се предполага, че са малко по-трудни и този случай е оставен на читателя да се досети сам за него.
